- uri: tag:light
  schema:
    type: //rec
    required:
      light:
        type: //rec
        required:
          read: //str
          write: //str
        optional:
          name: //str
- uri: tag:outlet
  schema:
    type: //rec
    required:
      outlet:
        type: //rec
        required:
          read: //str
          write: //str
        optional:
          name: //str
- uri: tag:blind_old
  schema:
    type: //rec
    required:
      blind_old:
        type: //rec
        required:
          read_top: //str
          read_bot: //str
          write_direction: //str
          write_stop: //str
        optional:
          name: //str
- uri: tag:blind
  schema:
    type: //rec
    required:
      blind:
        type: //rec
        required:
          read_position: //str
          write_position: //str
          write_direction: //str
          write_stop: //str
        optional:
          name: //str
