type: //rec
required:
  project: //str
  buildings:
#=================== building ====================
    type: //arr
    contents:
      type: //rec
      optional:
        name: //str
      required:
        url: //str
        floors:
#===================== floor =====================
          type: //arr
          contents:
            type: //rec
            optional:
              name: //str
            required:
              url: //str
              rooms:
#===================== room ======================
                type: //arr
                contents:
                  type: //rec
                  optional:
                    name: //str
                  required:
                    devices:
#=================== devices =====================
                      type: //arr
                      contents:
                        type: //any
                        of:
                        - tag:Light
                        - tag:Outlet
                        - tag:BlindOld
                        - tag:Blind
